### ISSUE TITLE
Way to display all widgets at homepage

### ISSUE THREAD

**Issue by robbertrosario** [junepaik/cadmium-cms#8]
Hi Junepaik,

Is there a way to like display all widgets or all variables at a certain page of your website? I am looking to display all the widgets on Index.tpl I know that I can use template tags such as { widget:block_1 / } but then I would have to keep inserting them by hand. I hope that you can help me with this.

thanks for this really wonderful cms by the way!

**Comment by ant-d3v** [comment]
Hi, Robbert. Thank you for using Cadmium! I'm proud to hear you like my CMS!

About your question, you can do it in a way like this...

You can create a group of widgets and insert it into template using the only template tag, for example: 

```
{ block:my_widgets / }
```

Insert it into desired place of the Index.tpl where you wish to display a group of widgets.
For now you can do it only by hand.

Then, unfortunately there are no methods to get a full list of widgets/variables for now. I'll add them in the next version for sure. But now you'll need to add them manually into file _/www/engine/Framework/Classes/Template/Template.php_.

```
// Get a list of global variables

public static function globals() {

    return self::$globals;
}

// Get a list of widgets

public static function widgets() {

    return self::$widgets;
}
```

Then you need to make some changes in _/www/engine/System/Classes/Frames/Site/Section.php_. Open the file and found method _getLayout_. The purpose of this method is to fill layout file (Index.tpl or Common.tpl for now) with programmatically generated blocks and variables.

Here an example of code that inserts a list of widgets into displayed layout.

```
// Create a group of widgets
$widgets_group = Template::group();

// Add widgets to group
foreach (Template::widgets() as $widget)  $widgets_group->add($widget);

// Insert group block into layout
$layout->my_widgets = $widgets_group;
```

Btw, i found some bugs in current version of cms and currently working on releasing new version 0.3. Please stay in touch for further updates!

**Comment by robbertrosario** [comment]
Hi,

Thanks! it works! is it also possible to have HTML around each widget?
I tried doing something like this, but it doesn't work:

```
{ block:my_widgets / }
<div class="ui card">
<h2>Title</h2>
<p>Body text</p>
</div>
{ / block:my_widgets }
```

And I will definitely follow this repo for upcoming updates. :+1:

**Comment by ant-d3v** [comment]
You can do it easily!

Template code:

```
{ block:my_widgets }
<div class="ui card">
    <h2>Title</h2>
    <p>{ block:contents / }</p>
</div>
{ / block:my_widgets }
```

PHP-code:

```
// Create a group container for widgets
$widgets_group = Template::group();

foreach (Template::widgets() as $widget_contents) {

    // Get widget block from template and clone it
    $widget_block = clone $layout->block('my_widgets');

    // Set widget contents
    $widget_block->contents = $widget_contents;

    // Add widget to group
    $widgets_group->add($widget_block);
}

// Replace initial widget block with a group of widgets
$layout->my_widgets = $widgets_group;
```

**Comment by robbertrosario** [comment]
Awesome! it works. Thanks a lot :)
